# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: jobA
    steps:
      - powershell: |
          $b = "http://www.bing.com"
          Write-Host "##vso[task.setvariable variable=t1;isOutput=true]$b"
        name: jobAOutput1
        displayName: set variable inline
      - task: PowerShell@2
        displayName: run powershell file
        timeoutInMinutes: 30
        inputs:
          filePath: test1.ps1
          arguments: -step '1' -p1 ''
        name: jobAOutput2
  - job: jobB
    dependsOn: ['jobA']
    variables:
      p1: $[ dependencies.jobA.outputs['jobAOutput1.t1'] ]
      p2: $[ dependencies.jobA.outputs['jobAOutput2.t2'] ]
    steps:
      - task: PowerShell@2
        displayName: run powershell file
        timeoutInMinutes: 30
        inputs:
          filePath: test1.ps1
          arguments: -step '2' -p1 '$(p1)'
      - powershell: |
          Write-Host "output p1(t1): $(p1)"
          Write-Host "output p2(t2): $(p2)"
          Write-Host "output t3: $Env:t3"


