# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: jobA
    steps:
      - powershell: |
          $b = "http://www.bing.com"
          Write-Host "##vso[task.setvariable variable=valuefiles;isOutput=true]$b"
        name: power
  - job: jobB
    dependsOn: ['jobA']
    steps:
      - powershell: |
          $va1 = $[dependencies.A.outputs['power.valuefiles']
          Write-Host "output: $va1"


