# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: jobA
    steps:
      - powershell: |
          $b = "http://www.bing.com"
          Write-Host "##vso[task.setvariable variable=t1;isOutput=true]$b"
  - job: jobB
    dependsOn: ['jobA']
    variables:
      var1: $[ dependencies.jobA.outputs['t1'] ]
    steps:
      - powershell: |
          Write-Host "output: $(var1)"


